apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
spec:
  selector:
    matchLabels:
      app: alpine
  replicas: 2
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
        - name: alpine
          image: mgresser1981/cloud_security_office_hours_demo:latest
          command:
            - /bin/sh
            - "-c"
            - "sleep 60m"
          imagePullPolicy: Always
          ports:
           - containerPort: 80
             name: nginx-svc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-svc